### ISSUE TITLE
License: Clarify timespan for forum non-response

### ISSUE THREAD

**Issue by mk-pmb** [StephanSteinert/AfraidOfTheDark#1]
Hi!
In case someone else might want to maintain it in the future, it would be nice to know when it's ok.
Also please write who can decide whether "this mod seems abandonned and not maintained anymore", e.g. replace "in case…" with "If you think…".

**Comment by StephanSteinert** [comment]
Well i got explicit permission from BinbinHfr to maintain it and got the needed rights on the mod portal on his mod.
This repo is at first only for managing my changes.

The mod is feature complete and needs only some love from time to time if an update of the game came out.

Abondoned means, no update for the current (including testing) version exits.

Do you want to maintain it?

**Comment by mk-pmb** [comment]
I don't currently see a need for another maintainer; I just want to make sure we properly prepare the transition while there is still someone alive and authorized to do it.
