### ISSUE TITLE
No commit history for this project?

### ISSUE THREAD

**Issue by Kallaste** [StephanSteinert/AfraidOfTheDark#2]
Thanks for the work on your mod. I was trying to view source code for previous releases of this project, since I am aware it has been ongoing for at least 3 years, but you seem to have no commit history that reflects changes to anything. According to the Factorio forums you have almost 2 dozen releases so far, right? I'm wondering, do you just delete everything in your repo and start from scratch every time you have a new release? Is this intentional?

I only ask because this would be very strange, since it isn't really how GitHub or SCM is supposed to work. Revision control systems exist to allow you to go back and look at changes to files . . . and your commit history seems to be gone. I was not sure if this was something you were going for or if you just weren't sure how to use GitHub for release versions.

If it isn't too much trouble, would mind pointing me toward the source from about 2 years ago for the Factorio 0.15 compatible release? Thanks a lot.

**Comment by StephanSteinert** [comment]
Hi,

thanks for your interest in this mod.

I inherited the Factorio 0.17 branch from binbinhfr - the original author of this mod.
As no git repo existed so far, i created this one and uploaded the latest version - so the blank history.

Older versions are listed here: https://mods.factorio.com/mod/AfraidOfTheDark/downloads and changes are posted here: https://mods.factorio.com/mod/AfraidOfTheDark

Cu, Stephan
